### ISSUE TITLE
Research effectiveness of state and local requests

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#566]
- [x] [How many are there across the different states and local government authorities?](https://github.com/openaustralia/righttoknow/issues/566#issuecomment-247234773) 302 (about 15% since we launched, 29% since the first state request was made)
- [x] [Are they replied to?](https://github.com/openaustralia/righttoknow/issues/566#issuecomment-247236644) By and large, yes. However 1 in 10 _don't_ get a response, which is pretty lame.
- [x] [Are they successful?](https://github.com/openaustralia/righttoknow/issues/566#issuecomment-247240988) Pretty much as much as federal requests are.
- [x] [Why are requests not being successful?](https://github.com/openaustralia/righttoknow/issues/566#issuecomment-248221339) Mainly because application fees/forms are demanded (50%), then because of no response (25%).
- [x] [Why are requests being successful?](https://github.com/openaustralia/righttoknow/issues/566#issuecomment-248512832) In about 60% of cases the authority is just doing the right thing and providing the information (not documents!) requested or a link to it.
- [x] [Why are so few Victorian requests marked as successful?](https://github.com/openaustralia/righttoknow/issues/566#issuecomment-248488619) There's not a massive amount of difference. This leads me to think Victoria is somewhat more aggressive in demanding application fees and because our numbers are so small they're looking more like an outlier than they really are.

**Comment by henare** [comment]
I've got a local copy of production that I can run against [my pull request](https://github.com/mysociety/alaveteli/pull/3483) to start getting this data. I think I'm going to create a Google Sheet with every request to state authorities to start with.

**Comment by henare** [comment]
I had a think about the fields we wanted and [wrote a scraper](https://morph.io/openaustralia/right_to_know_requests) to get all of it via the API.

This has the added advantage of allow @equivalentideas to feed his pivot table addiction with All The Data :bar_chart: 

I've [imported it](https://docs.google.com/spreadsheets/d/1OBYeRru8DqpB_41x8vyEaTRymfRXE2tRnr3LBxChNv0/edit#gid=1434967266) into Google Sheets.

**Comment by henare** [comment]
## How many are there across the different states and local government authorities?

As at 2016-09-15:

| Jurisdiction | Number of requests |
| --- | --- |
| Federal | 1736 (85%) |
| NSW | 199 (10%) |
| Victoria | 58 (3%) |
| ACT | 30 (1%) |
| NT | 11 (1%) |
| SA | 4 (<1%) |
| **TOTAL** | **2038** |

![RTK requests by jurisdiction](https://cloud.githubusercontent.com/assets/48945/18538764/c8e79cb4-7b54-11e6-94aa-9543bf7f5f80.png)

**Comment by henare** [comment]
## Are they being replied to?

Requests that have had at least 1 reply (this could be anything including an automated acknowledgement), as at 2016-09-15:

| Jurisdiction | Number of requests |
| --- | --- |
| Federal | 1643 (95%) |
| NSW | 171 (86%) |
| Victoria | 53 (91%) |
| ACT | 27 (90%) |
| NT | 6 (55%) |
| SA | 2 (50%) |
| Overall | 1902 (93%) |

**Comment by henare** [comment]
## Are they successful?

Requests displayed as "successful" or "partially successful", as at 2016-09-15:

| Jurisdiction | Number of requests |
| --- | --- |
| Federal | 488 (28%) |
| NSW | 49 (25%) |
| Victoria | 6 (10%) |
| ACT | 9 (33%) |
| NT | 3 (27%) |
| SA | 0 (0%) |
| Overall | 555 (27%) |

In 2014-2015, according to the OAIC there were a total of [5232 request for non-personal information received](https://oaic.gov.au/about-us/corporate-information/annual-reports/oaic-annual-report-201415/chapter-eight-agency-freedom-of-information#foi-requests-for-personal-information-and-for-other-information) and a total of [2099 were determined as "granted in full" or "granted in part"](https://oaic.gov.au/about-us/corporate-information/annual-reports/oaic-annual-report-201415/chapter-eight-agency-freedom-of-information#foi-requests-determined). That makes **the claimed federal success rate 40%**.

**Comment by equivalentideas** [comment]
## Why are requests not being successful?

To work this out we're going to:
1. define what `display_status`s are part of the unsuccessful category
2. go through all (or a lot of) the requests in that category and note our observations as to why they were unsuccessful
3. work out basic categories for these reasons so we can make generalisations about these reasons and answer this question

**Comment by henare** [comment]
Interesting research suggestion from @BR3NDA [on Twitter](https://twitter.com/BR3NDA/status/776961526565441538):

> Comparison of average charge, and % of zero charges, between agencies.

**Comment by henare** [comment]
> Why are requests not being successful?
> To work this out we're going to:
> 1. define what display_statuss are part of the unsuccessful category

I've done any that aren't classified as successful or partially successful.

> 1. go through all (or a lot of) the requests in that category and note our observations as to why they were unsuccessful

I've started this by doing ACT. I added a "Reason not successful" column to capture my findings.

> 1. work out basic categories for these reasons so we can make generalisations about these reasons and answer this question

In the 19 requests I looked at for the ACT I came across 9 different reasons:

> application form requested (3)
> charges imposed (1)
> documents already public (2)
> exemptions claimed (1)
> no response (3)
> not a request for documents (1)
> not held (7)
> too voluminous (1)

It's also worth noting that as I went I reclassified a few "refused" to "not held". I updated one request marked internal review that had received no response to "waiting response".

**Comment by henare** [comment]
## Why are requests not being successful?

I've now looked at every request on Right To Know to state/local authorities that is not marked as "successful" or "partially successful".

This chart shows simplified data about the reasons the requests were not successful:

![selection_001](https://cloud.githubusercontent.com/assets/48945/18660647/0021cfca-7f55-11e6-8f99-eceb0baff40b.png)

Simplified data:

> application form/fees requested 94
> no response 46
> not held  30
> requester issue 9
> delivery failure  5
> exemption claimed 5
> "claimed no request received" 2
> gone postal 1

**Comment by henare** [comment]
## Why are so few Victorian requests marked as successful?

This is the same chart as above but for only requests in Victoria - reasons requests have not been successful:

![selection_001](https://cloud.githubusercontent.com/assets/48945/18694819/91d8cd60-7ff0-11e6-8f3e-b9d9353b8bd6.png)

And the absolute numbers:

> application form/fees requested 26
> no response 8
> not held  4
> requester issue 2
> too voluminous  1

For comparison, here's **NSW**:

![selection_002](https://cloud.githubusercontent.com/assets/48945/18694951/b54c2f8e-7ff1-11e6-9efd-a662c2cfe73f.png)

There's not a massive amount of difference. This leads me to think Victoria is somewhat more aggressive in demanding application fees and because our numbers are so small they're looking more like an outlier than they really are.

**Comment by henare** [comment]
## Why are requests being successful?

I've classified all "successful" and "partially successful" requests now.

In this little analysis I've excluded ACT requests since their Act is very similar to the Federal Act and most importantly they don't have application fees.

It's _not because application fees are being paid_: Application fees have been paid on 11 requests. 3 of these requests have resulted in documents being published on RTK. 4 either went postal or got sent to the requester privately, 2 asked for further charges that the requester didn't pay, 1 didn't hold the documents, and 1 is still pending.

> documents provided 3
> went postal (fees paid) 2
> went private (fees paid) 2
> further charges requested 2
> not held 1
> pending 1

Here's the simplified reasons the request was successful for the remainder of the requests where the application fee wasn't paid:

![selection_001](https://cloud.githubusercontent.com/assets/48945/18698255/fd8c133a-800b-11e6-9e17-00714da0bc2a.png)

> documents provided  14
> information provided  15
> link provided 10
> went offsite  4

That overwhelmingly says it's because the authority is just choosing to do the right thing (for some reason) - in 35% of cases ("information provided") they're doing what would usually be classified as "creating documents" and is not required under the law even for formal requests. In 23% of cases ("link provided") they're helpfully pointing to already published information. And in 33% of cases ("documents provided") they're providing documents like they would have been required to do under the law (you could also argue the 9% of "went offsite" requests are in this category too).

**Comment by equivalentideas** [comment]
For interests sake, here's the proportion of reported federal government requests that went through Right To Know. Pretty cool. This uses data from the OIAC annual reports [2014](https://oaic.gov.au/about-us/corporate-information/annual-reports/oaic-annual-report-201415/chapter-eight-agency-freedom-of-information#foi-requests-for-personal-information-and-for-other-information) and [2015](https://oaic.gov.au/about-us/corporate-information/annual-reports/oaic-annual-report-201314/chapter-nine-agency-freedom-of-information) and the [2015-16 data released](http://data.gov.au/dataset/freedom-of-information-statistics).

| Financial year | Requests through Right To Know | Requests reported by Federal Government agencies | % of requests that used Right To Know |
| --- | --- | --- | --- |
| 12/13 | 255 | 5117 | 5% |
| 13/14 | 362 | 5773 | 6% |
| 14/15 | 432 | 5253 | 8% |
| 15/16 | 557 | 5394 | 10% |

**Comment by equivalentideas** [comment]
I just updated that [comment above](https://github.com/openaustralia/righttoknow/issues/566#issuecomment-249755633) ☝️ with the 2015/16 data from here http://data.gov.au/dataset/freedom-of-information-statistics/resource/6c3b7465-cf87-448c-8be5-afe5cd005f2f

10% of federal FOI requests in the period. Pretty awesome 🏆 🎉 🍹
